version: "20.10.12"
services:
dev-db:
image: postgres:13
ports:
- 5434:5432

enviroment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: 123
POSTGRES_DB: nest
networks:
- gohome
networks:


gohome:
test-db:
image: postgres:13
ports:
- 5435:5432

enviroment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: 123
POSTGRES_DB: nest
networks:
- gohome
networks:
gohome: